http://localhost:8080/products
http://localhost:8080/products/6a1245c348eb68befab721a0
http://localhost:8080/api-docs/

Render
https://storedb-wyw9.onrender.com/products
https://storedb-wyw9.onrender.com/products/6a1245c348eb68befab721a0
https://storedb-wyw9.onrender.com/api-docs/